#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/linuxserver/beets
  # -- image tag
  tag: 1.4.9-ls94@sha256:826263aebec32caed2bd3abe17fb26636b36c84ee27993aab14e11ed8a68fece
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [beets documentation](https://beets.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: custom
    subPath: config.yaml
    volumeSpec:
      configMap:
        name: beets-config
        items:
        - key: "config.yaml"
          path: "config.yaml"
  # data:
  #   enabled: false
  #   mountPath: /data

config:
  # Beets Config
  plugins: fetchart embedart scrub info web ipfs missing duplicates export inline
  directory: /music
  library: /music/library.db
  art_filename: albumart
  threaded: yes
  original_date: no
  per_disc_numbering: no

  scrub:
    auto: yes

  paths:
    default: $albumartist/$album [$year, $media, $format, $channels, $bitdepth-$samplerate] ($mb_albumid)/Disk $disc of $disctotal/$track $title ($length)
    singleton: $albumartist/$album [$year, $media, $format, $channels, $bitdepth-$samplerate] ($mb_albumid)/$track $title ($length)
    comp: Compilations/$album [$year, $media, $format, $channels, $bitdepth-$samplerate] ($mb_albumid)/Disk $disc of $disctotal/$track $title ($length)

  asciify_paths: yes
  replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''
    '[\\/]': _
    '^\s+': ''
    '^-': _

  web:
    host: 0.0.0.0
    port: 8337
    reverse_proxy: yes

  import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: yes
    log: /config/beet.log
    languages: en es fr
    detail: yes
    autotag: yes
    original_date: no

  fetchart:
    auto: yes

  embedart:
    auto: yes
