apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-client-config
  labels:
    app: roon
data:
  config.json: |
    {
      "version": "9",
      "hosts": {
        "minio": {
          "url": "http://192.168.1.69:30004",
          "accessKey": "AKIAIOSFODNN7EXAMPLE",
          "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
          "api": "s3v4",
          "lookup": "auto"
        }
      }
    }
