apiVersion: v2
name: transmission
description: A Helm chart for Kubernetes
type: application
version: 1.4.4
home: https://github.com/haugene/docker-transmission-openvpn
maintainers:
- name: jmmaloney4
  email: jmmaloney4@gmail.com
