forecastle:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.68"
  image:
    repository: docker.io/stakater/forecastle
    tag: 2.0.2@sha256:382cd9572352be83c28d44443daa6ba461fc4bdf6d8ce387ff0e5e2903c37bc6
  deployment:
    replicas: 1
    revisionHistoryLimit: 2
    annotations: {}
  config:
    namespaceSelector:
      any: true
    headerBackground:
    headerForeground:
    title:
    instanceName:
    customApps: {}
  proxy:
    enabled: false
  openshiftOauthProxy:
    enabled: false
    # image: stakater/oauth-proxy:v0.0.2
  service:
    annotations: {}
    expose: "false"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: forecastle.example.com
      paths:
      - /
  route:
    enabled: false
    annotations: {}
    additionalLabels: {}
    host: ""
    port:
      targetPort: http
    wildcardPolicy: None
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
