apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
      - name: delete-settings-json
        image: busybox
        volumeMounts:
        - mountPath: /data
          name: torrents
        args:
        - "rm"
        - "-f"
        - "/data/transmission-home/settings.json"
        - "/data/transmission-home/settings.json.tmp.*"
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: transmission
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        ports:
        - containerPort: 9091
          name: http
        livenessProbe:
          exec:
            command:
            - /etc/scripts/healthcheck.sh
          initialDelaySeconds: 60
          periodSeconds: 15
        env:
        # https://github.com/transmission/transmission/wiki/Editing-Configuration-Files
        - name: OPENVPN_PROVIDER
          value: {{ .Values.ovpn.provider | quote }}
        - name: OPENVPN_CONFIG
          value: {{ .Values.ovpn.config | quote }}
        - name: OPENVPN_USERNAME
          value: {{ .Values.ovpn.username | quote }}
        - name: OPENVPN_PASSWORD
          value: {{ .Values.ovpn.password | quote }}
        - name: OPENVPN_OPTS
          value: "--mssfix 1450 --mute-replay-warnings"
        - name: LOCAL_NETWORK
          value: "10.0.0.0/8,192.168.1.0/24"
        - name: WEBPROXY_ENABLED
          value: "false"
        - name: TRANSMISSION_WEB_UI
          value: {{ .Values.transmission.webui }}
        - name: CREATE_TUN_DEVICE
          value: "true"

        {{- if .Values.ovpn.dns1 }}
        - name: OVERRIDE_DNS_1
          value: {{ .Values.ovpn.dns1 }}
        {{- end }}
        {{- if .Values.ovpn.dns2 }}
        - name: OVERRIDE_DNS_2
          value: {{ .Values.ovpn.dns2 }}
        {{- end }}

        - name: TRANSMISSION_PEER_LIMIT_GLOBAL
          value: "{{ .Values.transmission.peer_limit_global }}"
        - name: TRANSMISSION_DOWNLOAD_QUEUE_ENABLED
          value: "false"
        - name: TRANSMISSION_QUEUE_STALLED_ENABLED
          value: "false"
        - name: TRANSMISSION_SEED_QUEUE_ENABLED
          value: "false"
        - name: TRANSMISSION_PREALLOCATION
          value: "0"
        - name: TRANSMISSION_PEER_SOCKET_TOS
          value: "{{ .Values.transmission.peer_socket_tos }}"
        - name: TRANSMISSION_ENCRYPTION
          value: "2"
        - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
          value: "true"
        - name: TRANSMISSION_DHT_ENABLED
          value: "{{ .Values.transmission.dht_enabled }}"
        - name: TRANSMISSION_PEX_ENABLED
          value: "{{ .Values.transmission.pex_enabled }}"
        - name: TRANSMISSION_LPD_ENABLED
          value: "{{ .Values.transmission.lpd_enabled }}"
        - name: TRANSMISSION_UTP_ENABLED
          value: "{{ .Values.transmission.utp_enabled }}"
        - name: TRANSMISSION_PORT_FORWARDING_ENABLED
          value: "true"
        - name: TRANSMISSION_PEER_PORT
          value: "{{ .Values.transmission.peer_port }}"
        - name: TRANSMISSION_RPC_URL
          value: "/{{ .Release.Name }}/transmission/"

        {{- if .Values.transmission.speed_limit_up }}
        - name: TRANSMISSION_SPEED_LIMIT_UP
          value: {{ .Values.transmission.speed_limit_up | quote }}
        - name: TRANSMISSION_SPEED_LIMIT_UP_ENABLED
          value: "true"
        {{- end }}

        {{- if .Values.transmission.speed_limit_down }}
        - name: TRANSMISSION_SPEED_LIMIT_DOWN
          value: {{ .Values.transmission.speed_limit_down | quote }}
        - name: TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED
          value: "true"
        {{- end }}

        volumeMounts:
        - mountPath: /data
          name: torrents
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        {{- if .Values.ovpn.mullvad_fix }}
        - mountPath: /scripts/openvpn-pre-start.sh
          name: script
          subPath: openvpn-pre-start.sh
        {{- end }}
      restartPolicy: Always
      volumes:
      - name: torrents
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: ovpn
        configMap:
          name: {{ .Release.Name }}-ovpn-file
      {{- if .Values.ovpn.mullvad_fix }}
      - name: script
        configMap:
          name: {{ .Release.Name }}-openvpn-pre-start-sh
          defaultMode: 0777
      {{- end }}
