{{- if .Values.minio.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: {{ .Release.Name }}-minio
spec:
  schedule: {{ .Values.minio.schedule }}
  jobTemplate:
    spec:
      template: 
        metadata:
          labels:
            app: {{ .Release.Name }}-minio
        spec:
          restartPolicy: OnFailure
          initContainers:
          - image: busybox
            name: make-directory
            args: ["mkdir", "-p", "/data/completed/"]
            volumeMounts:
            - mountPath: /data
              name: torrents
          - image: minio/mc:latest
            name: version
            args: ["--version"]
            volumeMounts:
            - mountPath: /root/.mc/config.json
              name: mc-config
              subPath: config.json
          - image: minio/mc:latest
            name: list-hosts
            args: ["config", "host", "list"]
            volumeMounts:
            - mountPath: /root/.mc/config.json
              name: mc-config
              subPath: config.json
          - image: minio/mc:latest
            name: make-bucket
            args: ["mb", "-p", "minio/{{ .Values.minio.bucket }}"]
            volumeMounts:
            - mountPath: /root/.mc/config.json
              name: mc-config
              subPath: config.json
          containers:
          - image: minio/mc:latest
            name: mirror
            args: ["mirror", "--watch", "--overwrite", "--exclude", "*.part", "/data/completed/", "minio/{{ .Values.minio.bucket }}/"]
            volumeMounts:
            - mountPath: /data
              name: torrents
              readOnly: true
            - mountPath: /root/.mc/config.json
              name: mc-config
              subPath: config.json
            resources:
              {{- toYaml .Values.minio.resources | nindent 14 }}
          volumes:
          - name: mc-config
            configMap:
              name: {{ .Release.Name }}-mc-config
          - name: torrents
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-data-pvc
{{- end}}
