apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openvpn-pre-start-sh
  labels:
    app: {{ .Release.Name }}
data:
  openvpn-pre-start.sh: |
    #!/bin/bash
    for file in /etc/openvpn/mullvad/*.ovpn; do 
      if [ -f "$file" ]; then 
        echo '\npull-filter ignore "dhcp-option DNS6"' >> "$file"
        echo 'pull-filter ignore "tun-ipv6"' >> "$file"
        echo 'pull-filter ignore "ifconfig-ipv6"' >> "$file" 
      fi
    done
