apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
      name: http
{{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
{{- end}}