apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roon.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "roon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "roon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "roon.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "roon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: roon
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.persistence.config.enabled }}
          - mountPath: /var/roon/
            name: config
          {{- end }}
          {{- if .Values.persistence.music.enabled }}
          - mountPath: /music/
            readOnly: true
            name: music
          {{- end }}
          {{- if .Values.persistence.backup.enabled }}
          - mountPath: /backups/
            name: backup
          {{- end }}
          {{- if .Values.persistence.cache.enabled }}
          - mountPath: /var/roon/RoonServer/Cache/
            name: cache
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.persistence.cache.enabled }}
      - name: cache
        emptyDir: {}
      {{- end}}

      {{- if .Values.persistence.config.enabled }}
      - name: config
        persistentVolumeClaim:
          claimName: {{ default (include "roon.pvc.config" .) .Values.persistence.config.existingClaim }}
      {{- end }}

      {{- if .Values.persistence.music.enabled }}
      - name: music
        persistentVolumeClaim:
          claimName: {{ default (include "roon.pvc.music" .) .Values.persistence.music.existingClaim }}
      {{- end }}

      {{- if .Values.persistence.backup.enabled }}
      - name: backup
        persistentVolumeClaim:
          claimName: {{ default (include "roon.pvc.backup" .) .Values.persistence.backup.existingClaim }}
      {{- end }}

      - name: minio-config
        configMap:
          name: minio-client-config

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
