apiVersion: v2
name: rclone
description: A Helm chart for Kubernetes
type: application
version: 2.2.2
home: https://rclone.org/
icon: https://rclone.org/img/logo_on_light__horizontal_color.svg
maintainers:
- name: jmmaloney4
  email: jmmaloney4@gmail.com
