schedule: "0 0/12 * * *"
successfulJobsHistoryLimit: 8
failedJobsHistoryLimit: 5
startingDeadlineSeconds: 43200  # 12 hours

image:
  repository: docker.io/rclone/rclone
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.73.2@sha256:8a17d9b5cd5ce71bbb42e49e92ee83575d7fb03f6233d949d328e9d029b9376d

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []

config: |
  # Rclone Config

toolbox: false  # Run container to be `kubectl exec`-ed into
subCommand: "copy"  # sync, delete, etc
args: []
from: ""
to: ""

volumeMounts: []
volumes: []
