schedule: "0 0/12 * * *"
successfulJobsHistoryLimit: 8
failedJobsHistoryLimit: 5
startingDeadlineSeconds: 43200  # 12 hours

image:
  repository: docker.io/rclone/rclone
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.74.2@sha256:9ce0d49b611d3781233e25334e9e23d7af01e5546da7087f90d55f034ef13637

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []

config: |
  # Rclone Config

toolbox: false  # Run container to be `kubectl exec`-ed into
subCommand: "copy"  # sync, delete, etc
args: []
from: ""
to: ""

volumeMounts: []
volumes: []
