schedule: "0 0/12 * * *"
successfulJobsHistoryLimit: 8
failedJobsHistoryLimit: 5
startingDeadlineSeconds: 43200  # 12 hours

image:
  repository: docker.io/rclone/rclone
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.73.4@sha256:654f6517c7aaec7e377690b2caf7c272dbe5f3b8200afbc14a00df6b4a9aa6ef

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []

config: |
  # Rclone Config

toolbox: false  # Run container to be `kubectl exec`-ed into
subCommand: "copy"  # sync, delete, etc
args: []
from: ""
to: ""

volumeMounts: []
volumes: []
