{{ $defaultRecords := .Values._defaultRecords }}
apiVersion: v1
kind: ConfigMap
metadata:
metadata:
  name: {{ include "ddclient.fullname" . }}-config
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
data:
{{- range .Values.hosts }}
  ddclient-{{ include "ddclient.login" . }}.conf: |
    daemon=600
    syslog=yes
    ssl=yes
    use=web
    web=dynamicdns.park-your-domain.com/getip
    protocol=namecheap
    server=dynamicdns.park-your-domain.com
    
    login={{ .login }}
    password={{ .password }}
    {{ range (.records | default $defaultRecords) }}{{ . }},{{ end }}
{{- end}}