# Default values for transmission.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: NodePort
  nodePort: 30007

## Persist data to a persistent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi
  annotations: 
    "helm.sh/resource-policy": keep
  storageClass: longhorn

