apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddclient.fullname" . }}
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{- include "ddclient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
{{- include "ddclient.selectorLabels" . | nindent 8 }}
    # Start of the pod spec
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "ddclient.serviceAccountName" . }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

{{ $image := .Values.image }}
# One container per host
{{- range .Values.hosts }}
        - name: {{ include "ddclient.login" . }}
          image: {{ $image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /config/ddclient.conf
            name: config
            subPath: ddclient-{{ include "ddclient.login" . }}.conf
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "ddclient.fullname" . }}-config