# Default values for Roon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jmmaloney4/roon
  # pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

persistence:
  config:
    enabled: true
    storageClass: "rook-ceph-block"
    size: "8Gi"
    accessMode: ReadWriteOnce
    annotations: 
      "helm.sh/resource-policy": keep
    # Uncomment to use an existing pvc
    # existingClaim:
  music:
    enabled: true
    storageClass: "rook-cephfs"
    size: "150Gi"
    accessMode: ReadWriteMany
    annotations:
      "helm.sh/resource-policy": keep
    # Uncomment to use an existing pvc
    # existingClaim:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

minio:
  enabled: false
  url: ""
  accessKey: ""
  secretKey: ""
  bucket: ""
  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 50m
    # limits:
    #   cpu: 250m
    #   memory: 512Mi