#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# Required for RAAT server to work
hostNetwork: true

image:
  # -- image repository
  repository: ghcr.io/jmmaloney4/roon
  # -- image tag
  tag: 1.8-806@sha256:29927df8ac0e5582de9f65da4ba302a2ddaa2918dc57f433e8983ff22cf6511f
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [roon documentation](https://roon.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /var/roon/
    size: 5Gi
    storageClass: "-"
    retain: true
  # music:
  #   enabled: false
  #   size: 300Gi
  #   storageClass: "-"
  # backups:
  #   enabled: false
  #   size: 20Gi
  #   storageClass: "-"
  ## Might cause a small speedup, not entirely clear. Depends on what you might have backing your config pvc.
  ## Test and see if you like it.
  # cache:
  #   enabled: false
  #   mountPath: /var/roon/RoonServer/Cache/
  #   type: emptyDir # Try hostPath too. Want something fast.
