name: Lint and Test Charts

on: 
- pull_request
- push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

#       - name: Set up Helm
#         uses: azure/setup-helm@v1.1

#       - uses: actions/setup-python@v2.2.2

#       - name: Set up chart-testing
#         uses: helm/chart-testing-action@v2.0.1

#       - name: Run chart-testing (list-changed)
#         id: list-changed
#         run: |
#           changed=$(ct list-changed --)
#           if [[ -n "$changed" ]]; then
#             echo "::set-output name=changed::true"
#           fi

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/ct.yaml
          
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
        
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/config/cf.yaml
