name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: roon

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      DATE: "$(date +\"%m-%d-%y\")"

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: jmmaloney4
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: jmmaloney4/roon
          tags: $DATE, latest
          path: image/
