name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: roon

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate date tag
        shell: bash
        run: date +\"%m-%d-%y\"
        id: gen_date
        
      - name: Print slug variables
        run: |
          echo ${{ steps.gen_date.output }}
          echo $(date +\"%m-%d-%y\")
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: jmmaloney4
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: jmmaloney4/roon
          tags: ${{ steps.gen_date.output }}, latest
          path: image/
