apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
  {{- if .Values.forecastle.openshiftOauthProxy.enabled }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"forecastle"}}'
  {{- end }}
  name: {{ template "forecastle.name" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forecastle.name" . }}-cluster-ingress-role
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
rules:
- apiGroups: ["", "route.openshift.io", "extensions"]
  resources: ["ingresses", "routes", "namespaces"]
  verbs: ["get", "list"]
- apiGroups:
  - forecastle.stakater.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "forecastle.name" . }}-cluster-ingress-role-binding
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "forecastle.name" . }}-cluster-ingress-role
subjects:
- kind: ServiceAccount
  name: {{ template "forecastle.name" . }}
  namespace: {{ .Release.Namespace }}
